export const REQUIRED:string = "This is required field"
export const NAMING:string = "Maximum 10 charecter"
export const MINIMUM_PASSWORD:string = "Password should be at least 6 charecters"
export const MAXIMUM_PASSWORD:string = "Password should not be axceeds to 10 chars"
export const BOTH_PASSWORD:string = "Both passwords need to be same"
export const ADRESS:string = "Address must be less than 31 chars"

export const SHOULD_BE_INTEGER:string = "Must be decimal value"
export const NONE_ZERO:string = "Cannot be zero"
export const MATCHES:string = "Must be only digits"
export const DIGITS_LENGTH:string = "Must be exactly 8 digits"